name = "heavy-trail-logistics"
compatibility_date = "2026-08-27"
pages_build_output_dir = "."

[[send_email]]
name = "QUOTE_EMAIL"
destination_address = "info@heavytraillogistics.com"
allowed_sender_addresses = ["quotes@heavytraillogistics.com"]